# Generated by Django 5.1.1 on 2024-09-20 13:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurturewell', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthmetrics',
            name='blood_pressure',
        ),
        migrations.RemoveField(
            model_name='healthmetrics',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='healthmetrics',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='healthmetrics',
            name='diastolic',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='healthmetrics',
            name='systolic',
            field=models.IntegerField(default=120),
        ),
    ]
